const express = require('express');
const router = express.Router();

const interestController = require('./interestController');

const CalendarController = require('./calendarController');
const PortfolioController = require('./portfolioController');
const profileController = require('./profileController');
const forexController = require('./forexController');
const stockController = require('./stockController');
const optionsController = require('./optionsController');
const trendsController = require('./trendsController');
const CommodityController = require('./CommodityController');
const earningController = require('./earningController');
const newsController = require('./newsController');
const ratioController = require('./ratioController');
const vixController = require('./vixController');
const screenerController = require('./screenerController');
const crossrateController = require('./crossrateController');
const volatilityController = require('./volatilityController');
const fnewsController = require('./fnewsController');
const openintrestController = require('./openintrestController');
const com_newsController = require('./com_newsController');

router.get('/interests', interestController.getAllInterests);
router.get('/forexs', forexController.getAllForexs);
router.get('/profiles', profileController.getAllProfiles);
router.get('/stocks', stockController.getAllStocks);
router.get('/options', optionsController.getOptions);
router.get('/trends', trendsController.getAllTrends);
router.get('/commodity', CommodityController.getCommodity);
router.get('/vix', vixController.getVix);
router.get('/crossrates', crossrateController.getCrossrate);
router.get('/earnings', earningController.getAllEarnings);
router.get('/news', newsController.getAllNews);
router.get('/fnews', fnewsController.getAllFnews);
router.get('/screener', screenerController.getAllScreener);
router.get('/com_news', com_newsController.getCom_news);
router.get('/ratios', ratioController.getAllRatios);
router.get('/openintrest', openintrestController.getOpenintrest);
router.get('/volatility', volatilityController.getAllVolatility);
router.get('/calendar', CalendarController.getAllCalendar);
router.get('/portfolio', PortfolioController.getAllPortfolio);
module.exports = router ;
